apiVersion: v1
kind: Pod
metadata:
  name: nettools
  namespace: default
  labels:
    app: watchdog
    kind: netcat
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: Always
    command: [ "sleep", "1200" ]
