# permissions for end users to view watchdogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: watchdog-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: watchdog
    app.kubernetes.io/part-of: watchdog
    app.kubernetes.io/managed-by: kustomize
  name: watchdog-viewer-role
rules:
- apiGroups:
  - net.post.ru
  resources:
  - watchdogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - net.post.ru
  resources:
  - watchdogs/status
  verbs:
  - get
